# Simple Monochrome
$active_border = rgb(bb9af7) rgb(16161e) rgb(16161e) rgb(bb9af7) 45deg
$inactive_border = rgb(414868) rgb(16161e) rgb(16161e) rgb(414868) 45deg
$wallpaper = ~/.config/assets/backgrounds/monochrome.png
