# Theme — visuals (colors, wallpaper)
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/theme.conf

# Theme — behavior (animations, gaps, blur, window rules)
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/behavior.conf

###################
### MY PROGRAMS  ###
###################

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun -theme ~/.config/rofi/rounded-nord-dark.rasi
$browser = zen-browser
$notes = obsidian
$editor = code
$editor-alt = subl
$colorPicker = hyprpicker

# Split config files
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/env.conf
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/autostart.conf
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/monitors.conf
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/binds.conf
source = /home/alban/dotfiles/themes/catppuccin/.config/hypr/rules.conf

#############
### INPUT ###
#############

input {
    kb_layout = fr
    follow_mouse = 1
    sensitivity = 0
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

gestures {
    gesture = 3, horizontal, workspace
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
