-- Generated by nwg-displays on 2026-06-25 at 13:41:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.01",
    position = "3072x0",
    scale = 1.25
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "4608x0",
    scale = 1.25
})
