
##############################
### WINDOWS AND WORKSPACES ###
##############################

# Use `hyprctl clients` to find window class names

# windowrulev2 = opacity 0.90 0.90, class:^(Thorium-browser)$
# windowrulev2 = opacity 0.80 0.80, class:^(Code)$
# windowrulev2 = opacity 0.80 0.80, class:^(obsidian)$
# windowrulev2 = opacity 0.80 0.70, class:^(pavucontrol)$
# windowrulev2 = opacity 0.80 0.70, class:^(blueman-manager)$
# windowrulev2 = opacity 0.70 0.70, class:^(Spotify)$

# windowrulev2 = float, class:^(kvantummanager)$
# windowrulev2 = float, class:^(qt5ct)$
# windowrulev2 = float, class:^(qt6ct)$
# windowrulev2 = float, class:^(nwg-look)$
# windowrulev2 = float, class:^(pavucontrol)$
# windowrulev2 = float, class:^(blueman-manager)$
# windowrulev2 = float, class:^(nm-applet)$
# windowrulev2 = float, class:^(nm-connection-editor)$

# windowrulev2 = suppressevent maximize, class:.*

# layerrule = blur, waybar
# layerrule = ignorezero, tofi
# layerrule = ignorezero, dunst
# layerrule = blur, dunst
