# Simple Monochrome
background_opacity 0.92

# The basic colors
foreground              #c0caf5
background              #16161e
selection_foreground    #16161e
selection_background    #bb9af7

# Cursor colors
cursor                  #bb9af7
cursor_text_color       #16161e

# URL underline color when hovering with mouse
url_color               #7aa2f7

# Kitty window border colors
active_border_color     #bb9af7
inactive_border_color   #414868
bell_border_color       #bb9af7

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #16161e
active_tab_background   #bb9af7
inactive_tab_foreground #c0caf5
inactive_tab_background #1a1b26
tab_bar_background      #16161e

# Colors for marks (marked text in the terminal)
mark1_foreground #16161e
mark1_background #c0caf5
mark2_foreground #16161e
mark2_background #bb9af7
mark3_foreground #16161e
mark3_background #7aa2f7

# The 16 terminal colors

# black
color0 #1a1b26
color8 #292e42

# red
color1 #f7768e
color9 #f7768e

# green
color2  #9ece6a
color10 #9ece6a

# yellow
color3  #414868
color11 #a9b1d6

# blue
color4  #7aa2f7
color12 #7aa2f7

# magenta
color5  #bb9af7
color13 #bb9af7

# cyan
color6  #7aa2f7
color14 #7aa2f7

# white
color7  #c0caf5
color15 #c0caf5
