# Base — shared, permanent config (keybinds, monitors, env, autostart, programs)
source = /home/alban/dotfiles/base/.config/hypr/programs.conf
source = /home/alban/dotfiles/base/.config/hypr/env.conf
source = /home/alban/dotfiles/base/.config/hypr/autostart.conf
source = /home/alban/dotfiles/base/.config/hypr/monitors.conf
source = /home/alban/dotfiles/base/.config/hypr/workspaces.conf
source = /home/alban/dotfiles/base/.config/hypr/binds.conf
source = /home/alban/dotfiles/base/.config/hypr/rules.conf

# Theme — visuals (colors, wallpaper)
source = /home/alban/dotfiles/themes/calm-blue/.config/hypr/theme.conf

# Theme — behavior (animations, gaps, blur, window rules)
source = /home/alban/dotfiles/themes/calm-blue/.config/hypr/behavior.conf

#############
### INPUT ###
#############

input {
    kb_layout = fr
    follow_mouse = 1
    sensitivity = 0
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

gestures {
    gesture = 3, horizontal, workspace
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
