# Calm Blue
$active_border = rgb(5c7fff) rgb(9a7dff) rgb(9a7dff) rgb(5c7fff) 45deg
$inactive_border = rgb(2c3a5c) rgb(0a0e1a) rgb(0a0e1a) rgb(2c3a5c) 45deg
$wallpaper = ~/.config/assets/backgrounds/Forest-Dark.png
