
#################
### AUTOSTART ###
#################

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/bin/dunst
exec-once = waybar
exec-once = awww-daemon
exec-once = [ -x ~/.config/hypr/wallpaper-daily.sh ] && ~/.config/hypr/wallpaper-daily.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridles
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Message platforms
exec-once = flatpak run com.discordapp.Discord --start-minimized
exec-once = teams-for-linux --minimized

# First app
exec-once = kitty
