####################
### MY PROGRAMS ###
####################

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun -modes drun -theme ~/.config/rofi/simple-monochrome.rasi
$browser = zen-browser
$notes = obsidian
$editor = code
$editor-alt = subl
$colorPicker = hyprpicker
