
##############################
### WINDOWS AND WORKSPACES ###
##############################

# Use `hyprctl clients` to find window class names
# New syntax: windowrule = <effect> <value>, match:<field> <value>

windowrule = opacity 0.70 0.60, match:class ^(kitty)$

# windowrule = opacity 0.90 0.90, match:class ^(zen-browser)$
# windowrule = opacity 0.80 0.80, match:class ^(Code)$
# windowrule = opacity 0.80 0.80, match:class ^(obsidian)$
# windowrule = opacity 0.80 0.70, match:class ^(pavucontrol)$
# windowrule = opacity 0.70 0.70, match:class ^(Spotify)$

# windowrule = float 1, match:class ^(kvantummanager)$
# windowrule = float 1, match:class ^(qt5ct)$
# windowrule = float 1, match:class ^(qt6ct)$
# windowrule = float 1, match:class ^(nwg-look)$
# windowrule = float 1, match:class ^(pavucontrol)$
# windowrule = float 1, match:class ^(blueman-manager)$
# windowrule = float 1, match:class ^(nm-applet)$
# windowrule = float 1, match:class ^(nm-connection-editor)$

# windowrule = suppressevent maximize, match:class .*

# layerrule = blur, waybar
# layerrule = ignorezero, tofi
# layerrule = ignorezero, dunst
# layerrule = blur, dunst
